name: Selenium and API tests
run-name: Run ${{ github.event.inputs.test_category }} tests

on:
  workflow_dispatch:
   inputs:
    test_category:
     description: 'Select test category'
     type: choice
     options:
     - All
     - API
     - UI
     required: true
  

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-latest  

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Execute all unit tests in the solution
    - name: Execute All test
      if: github.event.inputs.test_category == 'All'
      run: dotnet test

    - name: Execute API tests
      if: github.event.inputs.test_category == 'API'
      run: dotnet test --filter Category=API
      
    - name: Execute UI tests
      if: github.event.inputs.test_category == 'UI'
      run: dotnet test --filter Category=UI

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: WebDriverProject/bin/Debug/net8.0/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
          name: project
          path: WebDriverProject/bin/Debug
